(create) splash page component/profile skeleton
Quasi-Devs/Quasi-Bound pull request #8
Opened 2020-12-22 20:59 UTC by BenYoss

2020-12-23 15:54 UTC, jstrzesz requested changes

2020-12-23 15:54 UTC, jstrzesz commented on client/src/components/Navbar.jsx
> +          : (<Button variant="contained" color="primary" type="button" className={classes.profileButton} onClick={() => { window.location.href = '/profile'; }}>Profile</Button>)}
there are better ways to handle redirection, use react router

2020-12-23 15:54 UTC, jstrzesz commented on client/src/components/Profile/Profile.jsx
> +          <img src="https://lh3.googleusercontent.com/ogw/ADGmqu9MRmV9th8CboJblJP0PiUDHGVVMKHE5tnQV3sqZg=s192-c-mo" alt="" />
alt tag should have a value

2020-12-24 18:20 UTC, jstrzesz approved these changes

2020-12-24 18:23 UTC, agrem28 approved these changes

2020-12-24 18:24 UTC, merged